export const SCHEMA_VERSION = 3;
export const MAPPING_VERSION = 1;
export const LIBRARY_INDEX_KEY = "fv:library:index";
export const STATE_KEY_PREFIX = "fv:state:";
export const REPLAY_KEY_PREFIX = "fv:replay:";
export const ACTIVE_REPLAY_PREFIX = "fv:active-tab:";
export const MAX_IMPORT_BYTES = 1_000_000;
export const MAX_IMPORT_STATES = 250;
export const MAX_REPLAY_MS = 30_000;

export const MESSAGE = Object.freeze({
  GET_CAPTURE_PREVIEW: "GET_CAPTURE_PREVIEW",
  SAVE_CAPTURE: "SAVE_CAPTURE",
  LIST_STATES: "LIST_STATES",
  RENAME_STATE: "RENAME_STATE",
  DUPLICATE_STATE: "DUPLICATE_STATE",
  DELETE_STATE: "DELETE_STATE",
  EXPORT_LIBRARY: "EXPORT_LIBRARY",
  IMPORT_LIBRARY: "IMPORT_LIBRARY",
  START_REPLAY: "START_REPLAY",
  CANCEL_REPLAY: "CANCEL_REPLAY",
  GET_ACTIVE_REPLAY: "GET_ACTIVE_REPLAY",
  CAPTURE_PAGE: "CAPTURE_PAGE",
  EXECUTE_REPLAY: "EXECUTE_REPLAY",
  CANCEL_REPLAY_EXECUTOR: "CANCEL_REPLAY_EXECUTOR",
  CONTENT_READY: "CONTENT_READY",
  REPLAY_PROGRESS: "REPLAY_PROGRESS",
  REPLAY_COMPLETE: "REPLAY_COMPLETE"
});

export const CRITERION_ROLES = new Set(["FILTER", "CONTEXT", "PRESENTATION"]);
export const BINDING_TYPES = new Set(["URL_QUERY", "URL_PATH", "URL_FRAGMENT", "DOM", "ADAPTER"]);
export const CONTROL_TYPES = new Set([
  "BOOLEAN",
  "SINGLE_SELECT",
  "MULTI_SELECT",
  "NATIVE_SELECT",
  "TEXT_VALUE",
  "NUMERIC_VALUE",
  "BUTTON_OR_CHIP"
]);
export const ACTION_TYPES = new Set([
  "ENSURE_EXPANDED",
  "ACTIVATE_IF_NEEDED",
  "DEACTIVATE_IF_NEEDED",
  "SET_INPUT_VALUE",
  "SELECT_NATIVE_OPTION",
  "FOCUS",
  "SCROLL_CONTAINER",
  "WAIT_FOR_CONDITION",
  "VERIFY"
]);

export const CRITERION_STATUS = Object.freeze({
  ALREADY_APPLIED: "ALREADY_APPLIED",
  APPLIED: "APPLIED",
  VERIFIED: "VERIFIED",
  VALUE_UNAVAILABLE: "VALUE_UNAVAILABLE",
  FILTER_UNAVAILABLE: "FILTER_UNAVAILABLE",
  MAPPING_BROKEN: "MAPPING_BROKEN",
  RESOLUTION_INCONCLUSIVE: "RESOLUTION_INCONCLUSIVE",
  UNSUPPORTED_CONTROL: "UNSUPPORTED_CONTROL",
  UNSUPPORTED_INTERACTION: "UNSUPPORTED_INTERACTION",
  VERIFY_FAILED: "VERIFY_FAILED",
  DEPENDENCY_FAILED: "DEPENDENCY_FAILED",
  CANCELLED: "CANCELLED"
});

export const REPLAY_STATUS = Object.freeze({
  PLANNING: "PLANNING",
  WAITING_NAVIGATION: "WAITING_NAVIGATION",
  APPLYING: "APPLYING",
  VERIFYING: "VERIFYING",
  COMPLETE: "COMPLETE",
  COMPLETE_WITH_WARNINGS: "COMPLETE_WITH_WARNINGS",
  PARTIAL: "PARTIAL",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  INTERRUPTED: "INTERRUPTED"
});
